resolver: lts-9.20

packages: [.]

extra-deps:
- fmt-0.5.0.0
- haskell-names-0.9.0
- log-warper-1.8.2
- optparse-applicative-0.14.0.0
- path-0.6.1
- path-io-1.3.3
- universum-1.0.0

flags: {}
extra-package-dbs: []

nix:
    packages: [stack, binutils]
